import type { Metadata } from "next";
//import { Oswald, Roboto, Abril_Fatface } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import AuthProvider from "@/provider/AuthProvider";
import { ToasterProvider } from "@/utils/ToasterProvider";

// const roboto = Roboto({
//   weight: "400",
//   subsets: ["latin"],
// });

// const oswald = Oswald({
//   weight: ["400", "400", "500", "700"],
//   subsets: ["latin"],
// });
// const abriFatface = Abril_Fatface({
//   weight: "400",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-roboto font-oswald font-abril antialiased bg-white text-black">
        <ToasterProvider />
        <AuthProvider>
          <Navbar />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
