import type { Metadata } from "next";
import { Oswald, Roboto, Abril_Fatface } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

const oswald = Oswald({
  weight: ["400", "400", "500", "700"],
  subsets: ["latin"],
});
const abriFatface = Abril_Fatface({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${oswald.className} ${abriFatface.className} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
